# Generated by Django 2.1.7 on 2019-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': '主页轮播图'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='未设定', max_length=30, verbose_name='图片名称'),
        ),
    ]
