# Generated by Django 2.1.7 on 2019-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190502_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='图片名称'),
        ),
    ]
