# Generated by Django 2.1.7 on 2019-04-18 11:47

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='简介')),
                ('type', models.IntegerField(choices=[(1, '数码产品'), (2, '日用品'), (3, '服饰'), (4, '其他')], verbose_name='分类')),
                ('price', models.FloatField(verbose_name='价格')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('condition', goods.models.IntegerRangeField(verbose_name='新旧成色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('picture', models.CharField(max_length=2000, verbose_name='图片路径')),
                ('detail', models.CharField(max_length=2000, verbose_name='详细介绍')),
            ],
        ),
    ]
