# Generated by Django 2.1.7 on 2019-04-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190418_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='img', verbose_name='图片路径'),
        ),
    ]
