# Generated by Django 2.1.7 on 2019-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190419_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.CharField(max_length=1000, verbose_name='图片路径'),
        ),
    ]
