# Generated by Django 2.1.7 on 2019-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190420_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='want',
            field=models.CharField(max_length=1000, null=True, verbose_name='想换的'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.TextField(max_length=2000, null=True, verbose_name='详细介绍'),
        ),
    ]
