# Generated by Django 2.1.7 on 2019-04-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190425_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '交易中'), (2, '交易终止'), (3, '交易成功')], default=1, verbose_name='交易状态'),
        ),
    ]
