# Generated by Django 2.1.7 on 2019-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_mycollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '待沟通'), (2, '确认交易'), (3, '交易终止'), (4, '交易成功')], default=1, verbose_name='交易状态'),
        ),
    ]
