# Generated by Django 2.1.7 on 2019-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20190502_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='mycollection',
            options={'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单'},
        ),
        migrations.AddField(
            model_name='goods',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='是否被销售'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否下架'),
        ),
    ]
