# Generated by Django 2.1.7 on 2019-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_myuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='signature',
            field=models.CharField(default='这个人很懒，什么都没留下', max_length=200, verbose_name='个性签名'),
        ),
    ]
