# Generated by Django 2.1.7 on 2019-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_myuser_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='用户还没有设置地址', max_length=50, null=True, verbose_name='地址'),
        ),
    ]
