# Generated by Django 2.1.7 on 2019-04-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
