# Generated by Django 2.1.7 on 2019-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_auto_20190428_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_type',
        ),
    ]
